<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ibi115" name="TestScripts.CreateRequest" tests="10" failures="1" timestamp="02 Apr 2019 12:49:34 GMT" time="2160.056" errors="0">
  <testcase name="GroupRequestApprovalProcessbyUploadingSignersFile" time="254.361" classname="TestScripts.CreateRequest"/>
  <testcase name="GroupRequestApprovalProcess" time="265.336" classname="TestScripts.CreateRequest"/>
  <testcase name="CreateRequestSaveToDraft" time="150.304" classname="TestScripts.CreateRequest"/>
  <testcase name="RequestApprovalProcessWithMultipleSigners" time="270.404" classname="TestScripts.CreateRequest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at FrameworkLibrary.ReportLibrary.reportEvent(ReportLibrary.java:90)
at ApplicationPages.HomePage.clickonNeedToSign(HomePage.java:274)
at TestScripts.CreateRequest.RequestApprovalProcessWithMultipleSigners(CreateRequest.java:333)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- RequestApprovalProcessWithMultipleSigners -->
  <testcase name="RequestApprovalProcessWithSupportingDocuments" time="139.615" classname="TestScripts.CreateRequest"/>
  <testcase name="InPersonRequestCreation" time="148.232" classname="TestScripts.CreateRequest"/>
  <testcase name="RequestAttachmentRequiredAtTheTimeOfApproval" time="204.352" classname="TestScripts.CreateRequest"/>
  <testcase name="RequestApprovalProcessWithMultipleDocuments" time="213.953" classname="TestScripts.CreateRequest"/>
  <testcase name="TemplateCreationActivationAndRequestCreationApprovalProcess" time="301.835" classname="TestScripts.CreateRequest"/>
  <testcase name="RequestApprovalProcessWithSingleSigner" time="211.664" classname="TestScripts.CreateRequest"/>
</testsuite> <!-- TestScripts.CreateRequest -->
